### ISSUE TITLE
How to install jsfft

### ISSUE THREAD

**Issue by soundnerd** [dntj/jsfft#11]
Hi,

Excuse my ignorance I am new to JavaScript.  I am trying to install the jsfft library.  I tried using npm install jsfft but I got an error that jsfft cannot be a dependency of itself.  Do you know what is going on here or what I could do differently to get this library to install? 

Thanks,
Daniel Haverporth

**Comment by dntj** [comment]
Hmmm, I'm not an `npm` expert, but this worked for me (on OSX):

```
=> mkdir fft-demo
=> cd fft-demo/
=> npm install jsfft
...
+ jsfft@0.0.3
added 1 package in 0.979s
=> node
> require('jsfft')
{ ComplexArray: [Function: ComplexArray],
  FFT: [Function: FFT],
  InvFFT: [Function: InvFFT],
  frequencyMap: [Function: frequencyMap] } 
```
