### ISSUE TITLE
fft doesn't seem accurate compared to other libs

### ISSUE THREAD

**Issue by jsphweid** [dntj/jsfft#13]
Hi,

Something I do in python all the time is:

```python
import numpy
signal = [ 1, 1, 1, 1, 0, 0, 0, 0 ]
mags = abs(numpy.fft.fft(signal))[0:len(signal)//2]
print(mags)
# array([ 4.        ,  2.61312593,  0.        ,  1.0823922 ])
```

I'm trying to figure out how to do this here. I've managed to get this to work, but I'm not sure why I have to do it like this.
```javascript
const fft = require('./dist/fft')
const signal = [ 1, 1, 1, 1, 0, 0, 0, 0 ]
const mags = new fft.ComplexArray(signal.length)
	.map((value, index) => {
	    value.real = signal[index] * 2
	    value.imag = signal[index] * 2
	})
	.FFT()
	.magnitude()
	.slice(0, signal.length / 2)
console.log(mags)
//  [ 4, 2.613126039505005, 0, 1.0823922157287598 ]
```

Why do I have multiply everything by 2? or, needing to set both real / imag components seems wrong too.

**Comment by dntj** [comment]
Please compare [Numpy's FFT conventions](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.fft.html#implementation-details) with [those here](https://github.com/dntj/jsfft#conventions).  I believe they explain the difference you're seeing.
