### ISSUE TITLE
Example not working, missing bundle.js

### ISSUE THREAD

**Issue by pkerspe** [dntj/jsfft#14]
When trying to start the provided example in the browser, the bundle.js referenced in the index.html is missing.
Console Output is:
GET file:///Users/paul.kerspe/Downloads/jsfft-master/example/bundle.js net::ERR_FILE_NOT_FOUND

**Comment by msj121** [comment]
You need to use webpack to export the file bundle.js

https://webpack.js.org/guides/installation/

**Comment by dntj** [comment]
Thanks, I'll take a look.

**Comment by munrocket** [comment]
Can you create browser version too?
