### ISSUE TITLE
FFT vs InvFFT issue.

### ISSUE THREAD

**Issue by jedrzej-klocek** [dntj/jsfft#17]
Hello,
I am using your JS library for my application, and for me it is GREAT, but I found little problem :(.
I would compare your implementation between Matlab and Python Numpy implementation of FFT calculating.
For FFT magnitude and Real/Imag constellation of FFT it is not possible to find this issue. It was possible only when I try to compute angle of FFT. After comparison with Python and Matlab I think that your FFT and InvFFT methods are swapped. Problem is in line 119 and 157 in (1) +/- sign. I uploaded patch with problem solution, because I don't have access rights to repo.
Regards
Jedrzej

Attachments:
[patch.txt](https://github.com/dntj/jsfft/files/5459279/patch.txt)
![euler](https://user-images.githubusercontent.com/15615364/97589650-1636a680-19fe-11eb-88e2-5e2d19bcde01.png)
![DFTvsIFT](https://user-images.githubusercontent.com/15615364/97589656-18990080-19fe-11eb-8767-7c9ed613764f.png)

**Comment by dntj** [comment]
Thanks for the note.

Per the [docs](https://github.com/dntj/jsfft#conventions), this lib uses normalization and phase conventions common in physics which may differ from conventions in other disciplines.  You can use `ComplexArray.map` to convert between conventions.

**Comment by jedrzej-klocek** [comment]
Thanks for your response.
But I think that we didn't understand each other. For my is not a problem with normalization in your implementation because I know map method and I can fixed it. Problem is in sinus SIGN. I attached you Euler's formulas for e^(jPIkn) and e^(-jPIkn). Please look that simple FFT has "e^-j" in formula and InvFFT should have "e^j". In your recursive and iteration implementations sinus have opposite to attached formulas sign. So for me issue is not closed yet :/

**Comment by dntj** [comment]
I understand, but same goes for the phase, it's conventional, and you can use `map` to convert between conventions in frequency space.

**Comment by jedrzej-klocek** [comment]
Problem is not in normalization process but in definition of FFT and IFFT. So map is not a solution. Difference is in implementation of data prepare for fft in inverse condition for sinus. Please think about it, look at Euler formulas and FFT definition which was attached in main topic.
119 `var del_f_i = (inverse ? -1 : 1) * Math.sin(2 * PI * j / n);`
157 `var del_f_i = (inverse ? -1 : 1) * Math.sin(PI / width);`
If you not agree with this issue I have to fork your repo and change this two lines.

**Comment by dntj** [comment]
Just use a map negating the imaginary part to switch to your chosen convention.

**Comment by jedrzej-klocek** [comment]
Ok, thank you for your suggestion :) However I prefer my own fork because I work with 307.2k samples so every map cost me a lot of time and memory for computing.

**Comment by jedrzej-klocek** [comment]
Secondly in this way I can remove your normalization of square(N) which I do second time on result using `map` to optimize huge data computing. Thank's a lot for this discussion. Good luck!
