### ISSUE TITLE
ToDo in fft.js

### ISSUE THREAD

**Issue by philn5d** [dntj/jsfft#4]
There's a todo in the recursive transform. Can you possibly apply the multiplier while computing the output.real and output.imag values, then just swap them over to the input arrays (somehow)? Perhaps just ref the output arrays? input.real = output.real, etc...

**Comment by dntj** [comment]
Thanks for the question.  I think the trick is that you'd have to pass the input down to [the recursion](https://github.com/dntj/jsfft/blob/master/lib/fft.js#L92) which would need to work on a particular subset of the input which is doable but tricky.

But I may be wrong: give it a go and send me a PR if it works :smile:
