### ISSUE TITLE
How to apply InvFFT to image?

### ISSUE THREAD

**Issue by woshizja** [dntj/jsfft#5]
Thank you for your sharing。
I apply FFT to image like this：
`var afterFFT=fft.FFTImageDataRGBA(imgdata.data,img.width, img.height);`
I got `imgdata` from a canvas，imgdata.data is consist of rgba（not ComplexArray）。
Then，I got result（ComplexArray with real and imag），it seems right。
I want to apply INVFFT to the result， I try like this：
`var beforeFFT=fft.FFTImageDataRGBA(afterFFT, img.width, img.height, 1);`
But I got a wrong result：all of value are 0.
How can I apply InvFFT to the **afterFFT** ？
I reform the `fft.FFTImageDataRGBA = function(data, nx, ny)` to:
`fft.FFTImageDataRGBA = function(data, nx, ny, isInverse)`

**Comment by dntj** [comment]
Looking at the lib, it seems like that's not currently supported, the FFTImageDataRGBA would have to accept complex arrays.  Should be pretty easy to implement though.
