### ISSUE TITLE
npm package lacking build artifacts

### ISSUE THREAD

**Issue by nigel-smk** [dntj/jsfft#8]
Hello @dntj, 

I am trying to use your package on npm, but there is no code in it haha. 
When I build it from your repository and then sneak the dist folder into the module it works fine.

FYI this is breaking meyda @hughrawlinson

**Comment by 2xAA** [comment]
This appears to be incorrect, the package on npm does actually include the dist folder

**Comment by dntj** [comment]
Looks like this has been solved elsewhere.
